# Generated by Django 3.1.4 on 2021-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('order_items', models.ManyToManyField(to='example_api.Product')),
            ],
        ),
    ]
