# Generated by Django 3.1.4 on 2021-01-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_auto_20210121_1246'),
        ('example_api', '0007_category_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_product', to='shop_api.shop'),
            preserve_default=False,
        ),
    ]
