# Generated by Django 3.1.4 on 2021-01-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_auto_20210121_1246'),
        ('example_api', '0009_auto_20210121_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to='shop_api.shop'),
        ),
    ]
