# Generated by Django 3.1.4 on 2021-01-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_api', '0012_auto_20210121_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=42.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='item_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
