# Generated by Django 3.1.4 on 2021-01-18 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.CharField(blank=True, default='40min', max_length=70)),
                ('discount_coupon', models.CharField(blank=True, default='new_shop', max_length=128)),
                ('rating', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
