# Generated by Django 3.1.4 on 2021-01-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
